export {
    type AdminAuthenticateOptions,
    AdminAuthenticator,
    type Authenticator,
    UserAuthenticator,
} from './auth'
export { Cache, type CacheEntry, type CacheOptions } from './cache'
export {
    Client,
    type ClientEventHandler,
    type ClientEventMap,
    type ClientEventNames,
} from './client'
export {
    Gateway,
    type GatewayEventHandler,
    type GatewayEventMap,
    type GatewayEventNames,
    type GatewayOptions,
    GatewayStatus,
} from './gateway'
export {
    type AdminElectiveCounts,
    type AdminElectiveListEntry,
    ElectiveAdminActions,
    ElectiveManager,
    type FetchOptions,
    SelectionAdminActions,
    SelectionManager,
    SubjectAdminActions,
    SubjectManager,
    type SubjectMembersResult,
    TeamAdminActions,
    TeamManager,
    UserAdminActions,
    UserManager,
} from './managers'
export { RESTClient, type RESTOptions, type RequestOptions } from './rest'
export { Elective, Subject, Team, User } from './structures'
export {
    type AdminAddUserRequest,
    type AdminElectivePatch,
    type AdminListTeamsResponse,
    type AdminListUsersResponse,
    type AdminSetElectiveSubjectsRequest,
    type AdminSetStudentSelectionsRequest,
    type AdminSubjectPatch,
    type AdminTeamPatch,
    type AdminUserPatch,
    APIError,
    type AuthenticateRequest,
    type AuthenticateResponse,
    BadRequestError,
    type BulkSubjectEnrollmentUpdate,
    type ClientOptions,
    ConflictError,
    ForbiddenError,
    type ListElectivesResponse,
    type ListSubjectMembersResponse,
    type ListSubjectsResponse,
    type LoginOptions,
    NotFoundError,
    type NotificationEnvelope,
    type NotificationIdentify,
    RateLimitError,
    type RawElective,
    type RawSubject,
    type RawTeam,
    type RawUser,
    type SetStudentElectiveSelectionRequest,
    type StudentSelections,
    type SubjectEnrollmentUpdate,
    type SubjectEnrollmentUpdateSubscription,
    type SubjectEnrollmentUpdateSubscriptionRequest,
    SubjectTag,
    UnauthorizedError,
    UserType,
} from './types'
