export {
    type AdminAuthenticateOptions,
    AdminAuthenticator,
    type Authenticator,
    UserAuthenticator,
} from './auth'
export { Cache, type CacheEntry, type CacheOptions } from './cache'
export {
    Client,
    type ClientEventHandler,
    type ClientEventMap,
    type ClientEventNames,
} from './client'
export {
    Gateway,
    type GatewayEventHandler,
    type GatewayEventMap,
    type GatewayEventNames,
    type GatewayOptions,
    GatewayStatus,
} from './gateway'
export {
    type AdminEnrollmentCounts,
    type AdminEnrollmentListEntry,
    EnrollmentAdminActions,
    EnrollmentManager,
    type FetchOptions,
    GroupAdminActions,
    GroupManager,
    SelectionAdminActions,
    SelectionManager,
    SubjectAdminActions,
    SubjectManager,
    type SubjectMembersResult,
    UserAdminActions,
    UserManager,
} from './managers'
export { RESTClient, type RESTOptions, type RequestOptions } from './rest'
export { Enrollment, Group, Subject, User } from './structures'
export {
    type AdminAddUserRequest,
    AdminEnrollmentPatch,
    type AdminGroupPatch,
    type AdminListGroupsResponse,
    type AdminListUsersResponse,
    type AdminSetEnrollmentSubjectsRequest,
    type AdminSetStudentSelectionsRequest,
    type AdminSubjectPatch,
    type AdminUserPatch,
    APIError,
    type AuthenticateRequest,
    type AuthenticateResponse,
    BadRequestError,
    type BulkSubjectEnrollmentUpdate,
    type ClientOptions,
    ConflictError,
    ForbiddenError,
    GroupType,
    type ListEnrollmentsResponse,
    type ListSubjectMembersResponse,
    type ListSubjectsResponse,
    type LoginOptions,
    NotFoundError,
    type NotificationEnvelope,
    type NotificationIdentify,
    RateLimitError,
    type RawEnrollment,
    type RawGroup,
    type RawSubject,
    type RawUser,
    type SetStudentEnrollmentSelectionRequest,
    type StudentSelections,
    type SubjectEnrollmentUpdate,
    type SubjectEnrollmentUpdateSubscription,
    type SubjectEnrollmentUpdateSubscriptionRequest,
    SubjectTag,
    UnauthorizedError,
    UserType,
} from './types'
